# Generated by Django 4.2.5 on 2024-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='4476af283f', max_length=10, unique=True),
        ),
    ]
