# Generated by Django 4.2.5 on 2024-10-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0002_alter_classroom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='student',
        ),
        migrations.AddField(
            model_name='rubric',
            name='classroom_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='content_neatness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='knowledge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='performance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='punctuality_submission',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='4ac0c50cdc', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='rubric_file',
            field=models.ImageField(null=True, upload_to='rubrics/'),
        ),
    ]
