# Generated by Django 4.2.5 on 2024-10-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0003_remove_rubric_classroom_remove_rubric_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='classroom_id',
        ),
        migrations.AddField(
            model_name='rubric',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='rubric_app.classroom'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rubric_app.student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='b0d81a4614', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='content_neatness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='knowledge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='performance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='punctuality_submission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='rubric_file',
            field=models.ImageField(blank=True, null=True, upload_to='rubrics/'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
