# Generated by Django 4.2.5 on 2024-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0004_remove_rubric_classroom_id_rubric_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='24f5ac2a9e', max_length=10, unique=True),
        ),
    ]
