# Generated by Django 4.2.5 on 2024-11-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0005_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='fed2c6f741', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='rubric_app.student'),
        ),
    ]
