# Generated by Django 4.2.5 on 2024-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0009_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='42cd048210', max_length=10, unique=True),
        ),
    ]
