# Generated by Django 4.2.5 on 2025-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0010_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='cce9c5af1d', max_length=10, unique=True),
        ),
    ]
