# Generated by Django 4.2.5 on 2025-03-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_app', '0011_alter_classroom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='rubric_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Unique identifier for the student across all classrooms', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='c7b1f46607', max_length=10, unique=True),
        ),
    ]
